### ISSUE TITLE
测距完成后没有叉叉按钮，不可以删除测距线段

### ISSUE THREAD

**Issue by iamsmartloser** [huiyan-fe/BMapGLLib#10]
请问是否可以加上这个功能，跟2.0一致？

**Comment by Junior2Ran** [comment]
用的是最新的脚本么，之前有这个问题，现在已经修复了，更新下代码试试吧

**Comment by iamsmartloser** [comment]
&nbsp;




李艳
长虹网络学院


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月12日(星期一) 上午10:38
收件人: ***@***.***&gt;; 
抄送: "鬼　话　 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [huiyan-fe/BMapGLLib] 测距完成后没有叉叉按钮，不可以删除测距线段 (#10)





 
用的是最新的脚本么，之前有这个问题，现在已经修复了，更新下代码试试吧
