### ISSUE TITLE
怎么做才能不播放动画，直接显示轨迹

### ISSUE THREAD

**Issue by wemod123** [huiyan-fe/BMapGLLib#3]
TrackAnimation 这个包看起来很简洁，

如果想直接显示轨迹，怎么做呢，直接添加个overlay 吗

**Comment by Junior2Ran** [comment]
如果不播放动画指的是视角不跟随变化，可以直接自己在外面用rAF，循环执行polyline.setPath()方法
如果指的是线和视角都没有动画，那么就是直接添加个polyline的overlay

**Comment by wemod123** [comment]
有道理
