### ISSUE TITLE
使用轨迹动画生成的轨迹线中间会出现(0,0)的断点，渲染出来的线错误

### ISSUE THREAD

**Issue by lionel-king11** [huiyan-fe/BMapGLLib#34]
![image](https://user-images.githubusercontent.com/79784694/163405345-c9cd1e44-7695-4154-8750-b8d856ad4d9a.png)
![image](https://user-images.githubusercontent.com/79784694/163405446-05cff53b-65e4-4f7d-8b45-547260615349.png)

**Comment by FloraCat526** [comment]
建议过滤掉(0,0)这样的异常点

**Comment by liucdev** [comment]
使用未压缩源码版本是正常的，压缩源码有这个问题

**Comment by FloraCat526** [comment]
压缩版源码已更新
