### ISSUE TITLE
在多边形绘制状态下，双击地图会报错，导致绘制功能异常！还有getPath()方法获取的点位有偏差

### ISSUE THREAD

**Issue by Arthre** [huiyan-fe/BMapGLLib#35]

**Comment by Arthre** [comment]
![image](https://user-images.githubusercontent.com/38234304/164132755-307f9058-49da-439a-bb21-153bcb108b15.png)

**Comment by Arthre** [comment]
![image](https://user-images.githubusercontent.com/38234304/164133505-3739e14e-d7da-43d0-ac25-9f28d93b2262.png)
![image](https://user-images.githubusercontent.com/38234304/164133700-f517561d-4363-4b5e-869d-2588a413dc36.png)

**Comment by FloraCat526** [comment]
已修复

**Comment by sxc512599872** [comment]
功能未修复完，开启测距开关后依然报错。getPath()未获取值错误
![image](https://github.com/huiyan-fe/BMapGLLib/assets/57426070/62597ee3-343e-4726-aa6a-73c23d8f0c77)
![image](https://github.com/huiyan-fe/BMapGLLib/assets/57426070/ef5d5fb4-653e-45fc-9dac-0222207a97c3)
