### ISSUE TITLE
鼠标绘制的编辑模式

### ISSUE THREAD

**Issue by wemod123** [huiyan-fe/BMapGLLib#4]
使用·鼠标绘制·模块时，如果在绘制完成确认后，如何进编辑模式呢？

当前可以在绘制完成的事件中获取绘制图形，然后调 `overlay` 的 `enableEditing()`  方法实现功能，但是如果想使用 `DrawingManager` 的编辑状态（在绘制过程中，确认完成之前的状态），如何实现？

**Comment by Junior2Ran** [comment]
如果点击√之前是**绘制中**，点击√之后是**绘制完成**
**绘制中**时，覆盖物本身就处于编辑状态，能够编辑
**绘制完成**后，可以通过你上面说的在回调中使用`enableEditing`来实现

**Comment by wemod123** [comment]
多谢大神回复，

功能上是可以通过 `enableEditing` 实现的，我原来想要做的是回到`DrawingManager `的编辑状态（主要针对圆形）

例如，当完成一个圆的绘制后，通过 `enableEditing` 进入编辑状态时，就是通过拖拽2个点来编辑，不像在创建圆时，可以通过圆心和半径来做，UI相当友好。
我看了一下源码，其实可以把画好的这个圆反向传回到 `DrawingManager.prototype._bindCircle` 这个函数中，来初始化圆，跳过能过 `startAction` 初始化圆的过程，那么就可以直接进入 `DrawingManager` 的编辑状态。

其它的多边形等直接用 `enableEditing`  编辑界面差不多，就是画圆的这个差点，我再研究一下。
